Config = {}
Config.Locale = 'en'
Config.DrawDistance = 1.5
Config.AntiCombatLog              = false
Config.EarlyRespawnTimer          = 5 * (60 * 1000)
Config.BleedoutTimer              = 2 * (60 * 1000)
Config.ReviveReward 			  = 200
Config.RemoveWeaponsAfterRPDeath  = true
Config.RemoveCashAfterRPDeath     = true
Config.RemoveItemsAfterRPDeath    = true
Config.Jobs = {}
