Config = {
    ["UsingLoader"]     = false,
    
    ["UsingESX"]        = true,
    ["UsingESX_V1.2.0"] = false,
    ["UsingKashacters"] = false,
    ["CashAccountName"] = "money",
    ["BankAccountName"] = "bank",
}

Controls = {
  Focus = 185,
  Grab = 24,
}

furni = {}

furni.objects = {
  ["Sofás"] = {
    [1] = { ["object"] = "miss_rub_couch_01", ["price"] = 50, ["name"] = "Sofá Velho Flores" },
    [2] = { ["object"] = "prop_fib_3b_bench", ["price"] = 100, ["name"] = "Sofá 3 Lugares" },
    [3] = { ["object"] = "prop_ld_farm_chair01", ["price"] = 250, ["name"] = "Sofá Velho 1 Lugar" },
    [4] = { ["object"] = "prop_ld_farm_couch01", ["price"] = 50, ["name"] = "Sofá Velho 3 Lugares" },
    [5] = { ["object"] = "prop_ld_farm_couch02", ["price"] = 50, ["name"] = "Sofá Velho Riscas" },
    [6] = { ["object"] = "v_res_d_armchair", ["price"] = 50, ["name"] = "Sofá Velho Amarelo 1 Lugar" },
    [7] = { ["object"] = "v_res_fh_sofa", ["price"] = 200, ["name"] = "Sofá Canto" },
    [8] = { ["object"] = "v_res_mp_sofa", ["price"] = 200, ["name"] = "Sofá Canto2" },
    [9] = { ["object"] = "v_res_d_sofa", ["price"] = 100, ["name"] = "Sofá 1" },
    [10] = { ["object"] = "v_res_j_sofa", ["price"] = 100, ["name"] = "Sofá 2" },
    [11] = { ["object"] = "v_res_mp_stripchair", ["price"] = 100, ["name"] = "Sofá 3" },
    [12] = { ["object"] = "v_res_m_h_sofa_sml", ["price"] = 100, ["name"] = "Sofá 4" },
    [13] = { ["object"] = "v_res_r_sofa", ["price"] = 100, ["name"] = "Sofá 5" },
    [14] = { ["object"] = "v_res_tre_sofa", ["price"] = 100, ["name"] = "Sofá 6" },
    [15] = { ["object"] = "v_res_tre_sofa_mess_a", ["price"] = 100, ["name"] = "Sofá 7" },
    [16] = { ["object"] = "v_res_tre_sofa_mess_b", ["price"] = 100, ["name"] = "Sofá 8" },
    [17] = { ["object"] = "v_res_tre_sofa_mess_c", ["price"] = 100, ["name"] = "Sofá 9" },
    [18] = { ["object"] = "v_res_tt_sofa", ["price"] = 100, ["name"] = "Sofá 10" },
    [19] = { ["object"] = "prop_rub_couch02", ["price"] = 100, ["name"] = "Sofá 11" },
    [20] = { ["object"] = "apa_mp_h_stn_foot_stool_02", ["price"] = 250, ["name"] = "Sofá pés 1" },
    [21] = { ["object"] = "apa_mp_h_stn_foot_stool_01", ["price"] = 250, ["name"] = "Sofá pés 2" },
  },

  ["Cadeiras"] = {
    [1] = { ["object"] = "v_res_d_highchair", ["price"] = 100, ["name"] = "Cadeira Alta" },
    [2] = { ["object"] = "v_res_fa_chair01", ["price"] = 100, ["name"] = "Cadeira" },
    [3] = { ["object"] = "v_res_fa_chair02", ["price"] = 100, ["name"] = "Cadeira 2" },
    [4] = { ["object"] = "v_res_fh_barcchair", ["price"] = 100, ["name"] = "Cadeira Alta 2" },
    [5] = { ["object"] = "v_res_fh_dineeamesa", ["price"] = 100, ["nadme"] = "Cadeira Jantar 1" },
    [6] = { ["object"] = "v_res_fh_dineeamesb", ["price"] = 100, ["name"] = "Cadeira Jantar 2" },
    [7] = { ["object"] = "v_res_fh_dineeamesc", ["price"] = 100, ["name"] = "Cadeira Jantar 3" },
    [8] = { ["object"] = "v_res_fh_easychair", ["price"] = 100, ["name"] = "Cadeira 3" },
    [9] = { ["object"] = "v_res_fh_kitnstool", ["price"] = 100, ["name"] = "Banco Alto" },
    [10] = { ["object"] = "v_res_fh_singleseat", ["price"] = 100, ["name"] = "Cadeira Alta 2" },
    [11] = { ["object"] = "v_res_jarmchair", ["price"] = 100, ["name"] = "Cadeirão" },
    [12] = { ["object"] = "v_res_j_dinechair", ["price"] = 100, ["name"] = "Cadeira4" },
    [13] = { ["object"] = "v_res_j_stool", ["price"] = 100, ["name"] = "Banco Alto 2" },
    [14] = { ["object"] = "v_res_mbchair", ["price"] = 100, ["name"] = "Cadeira Leitura" },
    [15] = { ["object"] = "v_res_m_armchair", ["price"] = 100, ["name"] = "Cadeirão 2" },
    [16] = { ["object"] = "v_res_m_dinechair", ["price"] = 100, ["name"] = "Cadeira Jantar 4" },
    [17] = { ["object"] = "v_res_study_chair", ["price"] = 100, ["name"] = "Cadeira de Estudo" },
    [18] = { ["object"] = "v_res_trev_framechair", ["price"] = 100, ["name"] = "Cadeira Metal" },
    [19] = { ["object"] = "v_res_tre_chair", ["price"] = 100, ["name"] = "Cadeira 5" },
    [20] = { ["object"] = "v_res_tre_officechair", ["price"] = 100, ["name"] = "Cadeira Escritório" },
    [21] = { ["object"] = "v_res_tre_stool", ["price"] = 100, ["name"] = "Banco Alto" },
    [22] = { ["object"] = "v_res_tre_stool_leather", ["price"] = 100, ["name"] = "Banco de Pele" },
    [23] = { ["object"] = "v_res_tre_stool_scuz", ["price"] = 100, ["name"] = "Banco Partido" },
    [24] = { ["object"] = "v_med_p_deskchair", ["price"] = 100, ["name"] = "Cadeira Secretária" },
    [25] = { ["object"] = "v_med_p_easychair", ["price"] = 100, ["name"] = "Cadeirão 3" },
    [26] = { ["object"] = "v_med_whickerchair1", ["price"] = 100, ["name"] = "Cadeirão 4" },
    [27] = { ["object"] = "prop_direct_chair_01", ["price"] = 100, ["name"] = "Cadeira Pano 1" },
    [28] = { ["object"] = "prop_direct_chair_02", ["price"] = 100, ["name"] = "Cadeira Pano 2" },
    [29] = { ["object"] = "prop_yacht_lounger", ["price"] = 100, ["name"] = "Espreguiçadeira" },
    [30] = { ["object"] = "prop_yacht_seat_01", ["price"] = 100, ["name"] = "Espreguiçadeira 2" },
    [31] = { ["object"] = "prop_yacht_seat_02", ["price"] = 100, ["name"] = "Espreguiçadeira 3" },
    [32] = { ["object"] = "prop_yacht_seat_03", ["price"] = 100, ["name"] = "Espreguiçadeira 4" },
    [33] = { ["object"] = "v_ret_chair_white", ["price"] = 100, ["name"] = "Cadeira Branca" },
    [34] = { ["object"] = "v_ret_chair", ["price"] = 100, ["name"] = "Cadeira 6" },
    [35] = { ["object"] = "v_ret_ta_stool", ["price"] = 100, ["name"] = "Banco" },
    [36] = { ["object"] = "prop_cs_office_chair", ["price"] = 100, ["name"] = "Cadeira Escritório 2" },
  },

  ["Camas"] = {
    [1] = { ["object"] = "v_res_d_bed", ["price"] = 100, ["name"] = "Cama 1" },  
    [2] = { ["object"] = "v_res_lestersbed", ["price"] = 100, ["name"] = "Cama 2" }, 
    [3] = { ["object"] = "v_res_mbbed", ["price"] = 100, ["name"] = "Cama 3" }, 
    [4] = { ["object"] = "v_res_mdbed", ["price"] = 100, ["name"] = "Cama 4" }, 
    [5] = { ["object"] = "v_res_msonbed", ["price"] = 100, ["name"] = "Cama 5" },  
    [6] = { ["object"] = "v_res_tre_bed1", ["price"] = 100, ["name"] = "Cama 6" }, 
    [7] = { ["object"] = "v_res_tre_bed2", ["price"] = 100, ["name"] = "Cama 7" }, 
    [8] = { ["object"] = "v_res_tt_bed", ["price"] = 100, ["name"] = "Cama 8" },
    [9] = { ["object"] = "apa_mp_h_bed_double_08", ["price"] = 100, ["name"] = "Cama 9" },  
    [10] = { ["object"] = "apa_mp_h_bed_double_09", ["price"] = 100, ["name"] = "Cama 10" },
    [11] = { ["object"] = "apa_mp_h_bed_wide_05", ["price"] = 100, ["name"] = "Cama 11" },
    [12] = { ["object"] = "apa_mp_h_bed_with_table_02", ["price"] = 1000, ["name"] = "Cama Mesa" },
    [13] = { ["object"] = "gr_prop_bunker_bed_01", ["price"] = 500, ["name"] = "Cama Solteiro" },
  },

  ["Geral #1"] = {
    [1] = { ["object"] = "v_corp_facebeanbag", ["price"] = 100, ["name"] = "Puff" },
    [2] = { ["object"] = "v_res_cherubvase", ["price"] = 2500, ["name"] = "Vaso Branco" },
    [3] = { ["object"] = "v_res_d_paddedwall", ["price"] = 50, ["name"] = "Brinquedo Sexual" },
    [4] = { ["object"] = "v_res_d_ramskull", ["price"] = 50, ["name"] = "Esqueleto" },
    [5] = { ["object"] = "v_res_d_whips", ["price"] = 50, ["name"] = "Chicotes" },
    [6] = { ["object"] = "v_res_fashmag1", ["price"] = 50, ["name"] = "Revistas" },
    [7] = { ["object"] = "v_res_fashmagopen", ["price"] = 50, ["name"] = "Revistas 2" },
    [8] = { ["object"] = "v_res_fa_magtidy", ["price"] = 50, ["name"] = "Revistas 3" },
    [9] = { ["object"] = "v_res_fa_yogamat002", ["price"] = 50, ["name"] = "Tapete Yoga" },
    [10] = { ["object"] = "v_res_fa_yogamat1", ["price"] = 50, ["name"] = "Tapete Yoga 2" },
    [11] = { ["object"] = "v_res_fh_aftershavebox", ["price"] = 50, ["name"] = "Aftershave" },
    [12] = { ["object"] = "v_res_fh_flowersa", ["price"] = 50, ["name"] = "Flores" },
    [13] = { ["object"] = "v_res_fh_fruitbowl", ["price"] = 50, ["name"] = "Taça Fruta" },
    [14] = { ["object"] = "v_res_fh_laundrybasket", ["price"] = 50, ["name"] = "Cesto de Roupa" },
    [15] = { ["object"] = "v_res_fh_pouf", ["price"] = 50, ["name"] = "Pouf" },
    [16] = { ["object"] = "v_res_fh_sculptmod", ["price"] = 50, ["name"] = "Escultura" },
    [17] = { ["object"] = "v_res_j_magrack", ["price"] = 50, ["name"] = "Cesto de Roupa" },
    [18] = { ["object"] = "v_res_jewelbox", ["price"] = 50, ["name"] = "Caixa de Joias" },
    [19] = { ["object"] = "v_res_mbbin", ["price"] = 50, ["name"] = "Lixo" },
    [20] = { ["object"] = "v_res_mbowlornate", ["price"] = 50, ["name"] = "Taça" },
    [21] = { ["object"] = "v_res_mbronzvase", ["price"] = 50, ["name"] = "Vaso Bronze" },
    [22] = { ["object"] = "v_res_mchalkbrd", ["price"] = 50, ["name"] = "Quadro Giz" },
    [23] = { ["object"] = "v_res_mddresser", ["price"] = 50, ["name"] = "Roupeiro" },
    [24] = { ["object"] = "v_res_mplinth", ["price"] = 50, ["name"] = "Coluna" },
    [25] = { ["object"] = "v_res_mp_ashtrayb", ["price"] = 50, ["name"] = "Cinzeiro" },
    [26] = { ["object"] = "v_res_m_candle", ["price"] = 50, ["name"] = "Vela" },
    [27] = { ["object"] = "v_res_m_candlelrg", ["price"] = 50, ["name"] = "Vela XL" },
    [28] = { ["object"] = "v_res_m_kscales", ["price"] = 50, ["name"] = "Balança" },
    [29] = { ["object"] = "v_res_tt_bedpillow", ["price"] = 50, ["name"] = "Almofada" },
    [30] = { ["object"] = "apa_p_h_acc_artwallm_04", ["price"] = 50, ["name"] = "Arte Parede 1" },
    [31] = { ["object"] = "apa_p_h_acc_artwallm_03", ["price"] = 50, ["name"] = "Arte Parede 2" },
    [32] = { ["object"] = "apa_p_h_acc_artwallm_01", ["price"] = 50, ["name"] = "Arte Parede 3" },
    [33] = { ["object"] = "apa_p_h_acc_artwalll_04", ["price"] = 50, ["name"] = "Arte Parede 4" },
    [34] = { ["object"] = "apa_p_h_acc_artwalll_03", ["price"] = 50, ["name"] = "Arte Parede 5" },
    [35] = { ["object"] = "apa_mp_h_acc_rugwooll_03", ["price"] = 50, ["name"] = "Tapete 1" },
    [36] = { ["object"] = "apa_mp_h_acc_rugwoolm_04", ["price"] = 50, ["name"] = "Tapete 2" },
    [37] = { ["object"] = "apa_mp_h_acc_rugwools_03", ["price"] = 50, ["name"] = "Tapete 3" },
    [38] = { ["object"] = "hei_heist_str_sideboardl_05", ["price"] = 100, ["name"] = "Cómoda"},
  },

  ["Geral #2"] = {
    [1] = { ["object"] = "prop_a4_pile_01", ["price"] = 100, ["name"] = "Folhas" },
    [2] = { ["object"] = "prop_amb_40oz_03", ["price"] = 100, ["name"] = "Cerveja" },
    [3] = { ["object"] = "prop_amb_beer_bottle", ["price"] = 100, ["name"] = "Cerveja 2" },
    [4] = { ["object"] = "prop_aviators_01", ["price"] = 100, ["name"] = "Oculos" },
    [5] = { ["object"] = "prop_barry_table_detail", ["price"] = 100, ["name"] = "Folhas" },
    [6] = { ["object"] = "prop_beer_box_01", ["price"] = 100, ["name"] = "Cervejas" },
    [7] = { ["object"] = "prop_binoc_01", ["price"] = 100, ["name"] = "Binoculos" },
    [8] = { ["object"] = "prop_blox_spray", ["price"] = 100, ["name"] = "Spray" },
    [9] = { ["object"] = "prop_bongos_01", ["price"] = 100, ["name"] = "Tambores" },
    [10] = { ["object"] = "prop_bong_01", ["price"] = 100, ["name"] = "Bongo" },
    [11] = { ["object"] = "prop_boombox_01", ["price"] = 100, ["name"] = "Rádio" },
    [12] = { ["object"] = "prop_bowl_crisps", ["price"] = 100, ["name"] = "Batatas Fritas" },
    [13] = { ["object"] = "prop_candy_pqs", ["price"] = 100, ["name"] = "Gomas" },
    [14] = { ["object"] = "prop_carrier_bag_01", ["price"] = 100, ["name"] = "Saco Compras" },
    [15] = { ["object"] = "prop_ceramic_jug_01", ["price"] = 100, ["name"] = "Vaso" },
    [16] = { ["object"] = "prop_cigar_pack_01", ["price"] = 100, ["name"] = "Pack Cigarros 1" },
    [17] = { ["object"] = "prop_cigar_pack_02", ["price"] = 100, ["name"] = "Pack Cigarros 2" },
    [18] = { ["object"] = "prop_cs_beer_box", ["price"] = 100, ["name"] = "Caixa Cervejas 2" },
    [19] = { ["object"] = "prop_cs_binder_01", ["price"] = 100, ["name"] = "Dossier" },
    [20] = { ["object"] = "prop_cs_bs_cup", ["price"] = 100, ["name"] = "Copo" },
    [21] = { ["object"] = "prop_cs_cashenvelope", ["price"] = 100, ["name"] = "Envelope" },
    [22] = { ["object"] = "prop_cs_champ_flute", ["price"] = 100, ["name"] = "Flauta" },
    [23] = { ["object"] = "prop_cs_duffel_01", ["price"] = 100, ["name"] = "Mala Ginasio" },
    [24] = { ["object"] = "prop_cs_dvd", ["price"] = 50, ["name"] = "DVD" },
    [25] = { ["object"] = "prop_cs_dvd_case", ["price"] = 50, ["name"] = "DVD Caixa" },
    [26] = { ["object"] = "prop_cs_film_reel_01", ["price"] = 100, ["name"] = "Fita Filme" },
    [27] = { ["object"] = "prop_cs_ilev_blind_01", ["price"] = 100, ["name"] = "Cortinas" },
    [28] = { ["object"] = "p_ld_bs_bag_01", ["price"] = 100, ["name"] = "Mala" },
    [29] = { ["object"] = "prop_cs_ironing_board", ["price"] = 100, ["name"] = "Tabua Engomar" },
    [30] = { ["object"] = "prop_cs_katana_01", ["price"] = 100, ["name"] = "Katana" },
    [31] = { ["object"] = "prop_cs_kettle_01", ["price"] = 100, ["name"] = "Chaleira" },
    [32] = { ["object"] = "prop_cs_lester_crate", ["price"] = 100, ["name"] = "Caixa" },
    [33] = { ["object"] = "prop_cs_petrol_can", ["price"] = 100, ["name"] = "Jerrican" },
    [34] = { ["object"] = "prop_cs_sack_01", ["price"] = 100, ["name"] = "Saco" },
    [35] = { ["object"] = "prop_cs_script_bottle_01", ["price"] = 100, ["name"] = "Gararafa" },
    [36] = { ["object"] = "prop_cs_script_bottle", ["price"] = 100, ["name"] = "Garrafa 2" },
    [37] = { ["object"] = "prop_cs_street_binbag_01", ["price"] = 100, ["name"] = "Bin Bag" },
    [38] = { ["object"] = "prop_cs_whiskey_bottle", ["price"] = 100, ["name"] = "Whiskey" },
    [39] = { ["object"] = "prop_sh_bong_01", ["price"] = 100, ["name"] = "Bongo" },
    [40] = { ["object"] = "prop_peanut_bowl_01", ["price"] = 100, ["name"] = "Amendoins" },
    [41] = { ["object"] = "prop_tumbler_01", ["price"] = 100, ["name"] = "Copo Whiskey" },
  },
  
  ["Geral #3"] = {
    [1] = { ["object"] = "v_ret_csr_bin", ["price"] = 100, ["name"] = "Lixo" },
    [2] = { ["object"] = "v_ret_fh_wickbskt", ["price"] = 100, ["name"] = "Cesto" },
    [3] = { ["object"] = "v_ret_gc_bag01", ["price"] = 100, ["name"] = "Mala" },
    [4] = { ["object"] = "v_ret_gc_bag02", ["price"] = 100, ["name"] = "Mala" },
    [5] = { ["object"] = "v_ret_gc_bin", ["price"] = 100, ["name"] = "Lixo 2" },
    [6] = { ["object"] = "v_ret_gc_cashreg", ["price"] = 100, ["name"] = "Caixa Resitadora" },
    [7] = { ["object"] = "v_ret_gc_chair01", ["price"] = 100, ["name"] = "Cadeira" },
    [8] = { ["object"] = "v_ret_gc_chair02", ["price"] = 100, ["name"] = "Cadeira 2" },
    [9] = { ["object"] = "v_ret_gc_clock", ["price"] = 100, ["name"] = "Relógio" },
    [10] = { ["object"] = "v_ret_hd_prod1_", ["price"] = 100, ["name"] = "Prod 1" },
    [11] = { ["object"] = "v_ret_hd_prod2_", ["price"] = 100, ["name"] = "Prod 2" },
    [12] = { ["object"] = "v_ret_hd_prod3_", ["price"] = 100, ["name"] = "Prod 3" },
    [13] = { ["object"] = "v_ret_hd_prod4_", ["price"] = 100, ["name"] = "Prod 4" },
    [14] = { ["object"] = "v_ret_hd_prod5_", ["price"] = 100, ["name"] = "Prod 5" },
    [15] = { ["object"] = "v_ret_hd_prod6_", ["price"] = 100, ["name"] = "Prod 6" },
    [16] = { ["object"] = "v_ret_hd_unit1_", ["price"] = 100, ["name"] = "HD Unit 1" },
    [17] = { ["object"] = "v_ret_hd_unit2_", ["price"] = 100, ["name"] = "HD Unit 2" },
    [18] = { ["object"] = "v_ret_ml_fridge02", ["price"] = 100, ["name"] = "Frigorifico" },
    [19] = { ["object"] = "v_ret_ps_bag_01", ["price"] = 100, ["name"] = "Saco 1" },
    [20] = { ["object"] = "v_ret_ps_bag_02", ["price"] = 100, ["name"] = "Saco 2" },
    [21] = { ["object"] = "v_ret_ta_book1", ["price"] = 100, ["name"] = "Livro 1" },
    [22] = { ["object"] = "v_ret_ta_book2", ["price"] = 100, ["name"] = "Livro 2" },
    [23] = { ["object"] = "v_ret_ta_book3", ["price"] = 100, ["name"] = "Livro 3" },
    [24] = { ["object"] = "v_ret_ta_book4", ["price"] = 100, ["name"] = "Livro 4" },
    [25] = { ["object"] = "v_ret_ta_camera", ["price"] = 100, ["name"] = "Camera" },
    [26] = { ["object"] = "v_ret_ta_firstaid", ["price"] = 100, ["name"] = "Kit Médico" },
    [27] = { ["object"] = "v_ret_ta_hero", ["price"] = 100, ["name"] = "Heroi" },
    [28] = { ["object"] = "v_ret_ta_mag1", ["price"] = 100, ["name"] = "Revista 1" },
    [29] = { ["object"] = "v_ret_ta_mag2", ["price"] = 100, ["name"] = "Revista 2" },
    [30] = { ["object"] = "v_ret_ta_skull", ["price"] = 100, ["name"] = "Caveira" },
    [31] = { ["object"] = "prop_acc_guitar_01", ["price"] = 100, ["name"] = "Guitarra" },
    [32] = { ["object"] = "prop_amb_handbag_01", ["price"] = 100, ["name"] = "Mala De Mão" },
    [33] = { ["object"] = "prop_attache_case_01", ["price"] = 100, ["name"] = "Mala" },
    [34] = { ["object"] = "prop_big_bag_01", ["price"] = 100, ["name"] = "Mala Grande" },
    [35] = { ["object"] = "prop_bonesaw", ["price"] = 100, ["name"] = "Serra De Ossos" },
    [36] = { ["object"] = "prop_cs_fertilizer", ["price"] = 100, ["name"] = "Fertelizante" },
    [37] = { ["object"] = "prop_cs_shopping_bag", ["price"] = 100, ["name"] = "Saco De Compras" },
    [38] = { ["object"] = "prop_cs_vial_01", ["price"] = 100, ["Frasco"] = "Vial" },
    [39] = { ["object"] = "prop_defilied_ragdoll_01", ["price"] = 100, ["Boneca de Trapos"] = "Ragdoll" }, 
  },

  ["Geral #4"] = {
    [1] = { ["object"] = "prop_dummy_01", ["price"] = 100, ["name"] = "Boneca De Montra" },
    [2] = { ["object"] = "prop_egg_clock_01", ["price"] = 100, ["name"] = "Relogio Ovo" },
    [3] = { ["object"] = "prop_el_guitar_01", ["price"] = 100, ["name"] = "Guitarra 1" },
    [4] = { ["object"] = "prop_el_guitar_02", ["price"] = 100, ["name"] = "Guitarra 2" },
    [5] = { ["object"] = "prop_el_guitar_03", ["price"] = 100, ["name"] = "Guitarra 2" },
    [6] = { ["object"] = "prop_feed_sack_01", ["price"] = 100, ["name"] = "Saquinho" },
    [7] = { ["object"] = "prop_floor_duster_01", ["price"] = 100, ["name"] = "Aspirador" },
    [8] = { ["object"] = "prop_fruit_basket", ["price"] = 100, ["name"] = "Cesto De Fruta" },
    [9] = { ["object"] = "prop_f_duster_02", ["price"] = 100, ["name"] = "Espanador" },
    [10] = { ["object"] = "prop_grapes_02", ["price"] = 100, ["name"] = "Espanador" },
    [11] = { ["object"] = "prop_hotel_clock_01", ["price"] = 100, ["name"] = "Relógio De Hotel" },
    [12] = { ["object"] = "prop_idol_case_01", ["price"] = 100, ["name"] = "Caixa De Madeira" },
    [13] = { ["object"] = "prop_jewel_02a", ["price"] = 100, ["name"] = "Bijuteria 1" },
    [14] = { ["object"] = "prop_jewel_02b", ["price"] = 100, ["name"] = "Bijuteria 2" },
    [15] = { ["object"] = "prop_jewel_02c", ["price"] = 100, ["name"] = "Bijuteria 3" },
    [16] = { ["object"] = "prop_jewel_03a", ["price"] = 100, ["name"] = "Bijuteria 4" },
    [17] = { ["object"] = "prop_jewel_03b", ["price"] = 100, ["name"] = "Bijuteria 5" },
    [18] = { ["object"] = "prop_jewel_04a", ["price"] = 100, ["name"] = "Bijuteria 6" },
    [19] = { ["object"] = "prop_jewel_04b", ["price"] = 100, ["name"] = "Bijuteria 7" },
    [20] = { ["object"] = "prop_j_disptray_01", ["price"] = 100, ["name"] = "Bandeja de exibição 1" },
    [21] = { ["object"] = "prop_j_disptray_01b", ["price"] = 100, ["name"] = "Bandeja de exibição 2" },
    [22] = { ["object"] = "prop_j_disptray_02", ["price"] = 100, ["name"] = "Bandeja de exibição 3" },
    [23] = { ["object"] = "prop_j_disptray_03", ["price"] = 100, ["name"] = "Bandeja de exibição 4" },
    [24] = { ["object"] = "prop_j_disptray_04", ["price"] = 100, ["name"] = "Bandeja de exibição 5" },
    [25] = { ["object"] = "prop_j_disptray_04b", ["price"] = 100, ["name"] = "Bandeja de exibição 6" },
    [26] = { ["object"] = "prop_j_disptray_05", ["price"] = 100, ["name"] = "Bandeja de exibição 7" },
    [27] = { ["object"] = "prop_j_disptray_05b", ["price"] = 100, ["name"] = "Bandeja de exibição 8" },
    [28] = { ["object"] = "prop_ld_greenscreen_01", ["price"] = 100, ["name"] = "Green Screen" },
    [29] = { ["object"] = "prop_ld_handbag", ["price"] = 100, ["name"] = "Mala De Mao" },
    [30] = { ["object"] = "prop_ld_jerrycan_01", ["price"] = 100, ["name"] = "Jerry Can" },
    [31] = { ["object"] = "prop_ld_keypad_01", ["price"] = 100, ["name"] = "Keypad 1" },
    [32] = { ["object"] = "prop_ld_keypad_01b", ["price"] = 100, ["name"] = "Keypad 2" },
    [33] = { ["object"] = "prop_ld_suitcase_01", ["price"] = 100, ["name"] = "Mala 1" },
    [34] = { ["object"] = "prop_ld_suitcase_02", ["price"] = 100, ["name"] = "Mala 2" },
    [35] = { ["object"] = "hei_p_attache_case_shut", ["price"] = 100, ["name"] = "Mala 3"},
    [36] = { ["object"] = "prop_mr_rasberryclean", ["price"] = 100, ["name"] = "Urso De Peluche" },
    [37] = { ["object"] = "prop_paper_bag_01", ["price"] = 100, ["name"] = "Saco De Papel" },
    [38] = { ["object"] = "prop_shopping_bags01", ["price"] = 100, ["name"] = "Sacos De Compras" },
    [39] = { ["object"] = "prop_shopping_bags02", ["price"] = 100, ["name"] = "Sacos De Compras 2" },
    [40] = { ["object"] = "prop_yoga_mat_01", ["price"] = 100, ["name"] = "Tapete De Yoga 1" },
    [41] = { ["object"] = "prop_yoga_mat_02", ["price"] = 100, ["name"] = "Tapete De Yoga 2" },
    [42] = { ["object"] = "prop_yoga_mat_03", ["price"] = 100, ["name"] = "Tapete De Yoga 3" },
    [43] = { ["object"] = "p_ld_sax", ["price"] = 100, ["name"] = "Saxofone" },
    [44] = { ["object"] = "p_ld_soc_ball_01", ["price"] = 100, ["name"] = "Bola De Futebol" },
    [45] = { ["object"] = "p_watch_01", ["price"] = 100, ["name"] = "Relogio 1" },
    [46] = { ["object"] = "p_watch_02", ["price"] = 100, ["name"] = "Relogio 2" },
    [47] = { ["object"] = "p_watch_03", ["price"] = 100, ["name"] = "Relogio 3" },
    [48] = { ["object"] = "p_watch_04", ["price"] = 100, ["name"] = "Relogio 4" },
    [49] = { ["object"] = "p_watch_05", ["price"] = 100, ["name"] = "Relogio 5" },
    [51] = { ["object"] = "p_watch_06", ["price"] = 100, ["name"] = "Relogio 6" },
  },

  ["Pequenos Objetos"] = {
    [1] = { ["object"] = "v_res_r_figcat", ["price"] = 50, ["name"] = "Figura De Gato" },
    [2] = { ["object"] = "v_res_r_figclown", ["price"] = 50, ["name"] = "Figura De Palhaço" },
    [3] = { ["object"] = "v_res_r_figauth2", ["price"] = 50, ["name"] = "Quadro" },
    [4] = { ["object"] = "v_res_r_figfemale", ["price"] = 50, ["name"] = "Quadro De Mulher" },
    [5] = { ["object"] = "v_res_r_figflamenco", ["price"] = 50, ["name"] = "Figura De Flamengo" },
    [6] = { ["object"] = "v_res_r_figgirl", ["price"] = 50, ["name"] = "Figura Rapariga" },
    [7] = { ["object"] = "v_res_r_figgirlclown", ["price"] = 50, ["name"] = "Figura Rapariga Palhaço" },
    [8] = { ["object"] = "v_res_r_figoblisk", ["price"] = 50, ["name"] = "Figura Obilisk" },
    [9] = { ["object"] = "v_res_r_figpillar", ["price"] = 50, ["name"] = "Figura Pilar" },
    [10] = { ["object"] = "v_res_r_teapot", ["price"] = 50, ["name"] = "Chaleira" },
    [11] = { ["object"] = "v_res_sculpt_dec", ["price"] = 50, ["name"] = "Escultura 1" },
    [12] = { ["object"] = "v_res_sculpt_decd", ["price"] = 50, ["name"] = "Escultura 2" },
    [13] = { ["object"] = "v_res_sculpt_dece", ["price"] = 50, ["name"] = "Escultura 3" },
    [14] = { ["object"] = "v_res_sculpt_decf", ["price"] = 50, ["name"] = "Escultura 4" },
    [15] = { ["object"] = "v_res_skateboard", ["price"] = 50, ["name"] = "Skateboard" },
    [16] = { ["object"] = "v_res_sketchpad", ["price"] = 50, ["name"] = "Bloco De Desenho" },
    [17] = { ["object"] = "v_res_tissues", ["price"] = 50, ["name"] = "Lenços" },
    [18] = { ["object"] = "v_res_tre_basketmess", ["price"] = 50, ["name"] = "Cesta" },
    [19] = { ["object"] = "v_res_tre_bin", ["price"] = 50, ["name"] = "Lixo" },
    [20] = { ["object"] = "v_res_tre_cushiona", ["price"] = 50, ["name"] = "Almofada 1" },
    [21] = { ["object"] = "v_res_tre_cushionb", ["price"] = 50, ["name"] = "Almofada 2" },
    [22] = { ["object"] = "v_res_tre_cushionc", ["price"] = 50, ["name"] = "Almofada 3" },
    [23] = { ["object"] = "v_res_tre_cushiond", ["price"] = 50, ["name"] = "Almofada 4" },
    [24] = { ["object"] = "v_res_tre_cushnscuzb", ["price"] = 50, ["name"] = "Almofada 5" },
    [25] = { ["object"] = "v_res_tre_cushnscuzd", ["price"] = 50, ["name"] = "Almofada 6" },
    [26] = { ["object"] = "v_res_tre_fruitbowl", ["price"] = 50, ["name"] = "Taça De Fruta" },
    [27] = { ["object"] = "v_med_p_sideboard", ["price"] = 50, ["name"] = "Armario" },
    [28] = { ["object"] = "prop_idol_01", ["price"] = 100, ["name"] = "Estatua" },
    [29] = { ["object"] = "p_cs_cuffs_02_s", ["price"] = 100, ["name"] = "Algemas" },
    [30] = { ["object"] = "prop_cs_dildo_01", ["price"] = 100, ["name"] = "Mini Dildo" },
    [31] = { ["object"] = "v_res_d_dildo_a", ["price"] = 100, ["name"] = "Alien Dildo" },
    [32] = { ["object"] = "v_res_d_dildo_b", ["price"] = 100, ["name"] = "Dildo Maior" },
    [33] = { ["object"] = "v_res_d_dildo_c", ["price"] = 100, ["name"] = "OG Dildo" },
    [34] = { ["object"] = "v_res_d_lube", ["price"] = 100, ["name"] = "Lubrificante" },
    [35] = { ["object"] = "v_ret_gc_trays", ["price"] = 100, ["name"] = "Suporte Para Folhas" },
    [36] = { ["object"] = "v_res_filebox01", ["price"] = 100, ["name"] = "Caixa" },
  },

  ["Arrumação"] = {
    [1] = { ["object"] = "v_res_cabinet", ["price"] = 2500, ["name"] = "Armario Velho" },
    [2] = { ["object"] = "v_res_d_dressingtable", ["price"] = 2500, ["name"] = "Tocador" },
    [3] = { ["object"] = "v_res_d_sideunit", ["price"] = 2500, ["name"] = "Comoda Velha" },
    [4] = { ["object"] = "v_res_fh_sidebrddine", ["price"] = 2500, ["name"] = "Comoda Moderna" },
    [5] = { ["object"] = "v_res_fh_sidebrdlngb", ["price"] = 2500, ["name"] = "Comoda Moderna 2" },
    [6] = { ["object"] = "v_res_mbbedtable", ["price"] = 2500, ["name"] = "Cabeceira" },
    [7] = { ["object"] = "v_res_j_tvstand", ["price"] = 2500, ["name"] = "TV Com Comoda" },
    [8] = { ["object"] = "v_res_mbdresser", ["price"] = 2500, ["name"] = "Comoda" },
    [9] = { ["object"] = "v_res_mbottoman", ["price"] = 2500, ["name"] = "Bottoman Unit" },
    [10] = { ["object"] = "v_res_mconsolemod", ["price"] = 2500, ["name"] = "Comoda Velha" },
    [11] = { ["object"] = "v_res_mcupboard", ["price"] = 2500, ["name"] = "Mini Armario" },
    [12] = { ["object"] = "v_res_mdchest", ["price"] = 2500, ["name"] = "Comoda" },
    [13] = { ["object"] = "v_res_msoncabinet", ["price"] = 2500, ["name"] = "Suporte Para Tv"},
    [14] = { ["object"] = "v_res_m_armoire", ["price"] = 2500, ["name"] = "Armario" },
    [15] = { ["object"] = "v_res_m_sidetable", ["price"] = 2500, ["name"] = "Prateleira Com Espelho" },
    [16] = { ["object"] = "v_res_son_desk", ["price"] = 2500, ["name"] = "Secretária" },
    [17] = { ["object"] = "v_res_tre_bedsidetable", ["price"] = 2500, ["name"] = "Cabeceira 1" },
    [18] = { ["object"] = "v_res_tre_bedsidetableb", ["price"] = 2500, ["name"] = "Cabeceira 2" },
    [19] = { ["object"] = "v_res_tre_smallbookshelf", ["price"] = 2500, ["name"] = "Prateleira Para Livros" },
    [20] = { ["object"] = "v_res_tre_storagebox", ["price"] = 2500, ["name"] = "Box Unit" },
    [21] = { ["object"] = "v_res_tre_storageunit", ["price"] = 2500, ["name"] = "Caixa" },
    [22] = { ["object"] = "v_res_tre_wardrobe", ["price"] = 2500, ["name"] = "Armario" },
    [23] = { ["object"] = "v_res_tre_wdunitscuz", ["price"] = 2500, ["name"] = "Armario Lixado" },
    [24] = { ["object"] = "prop_devin_box_closed", ["price"] = 100, ["name"] = "Caixa" },
    [25] = { ["object"] = "prop_mil_crate_01", ["price"] = 100, ["name"] = "Caixa Militar" },
    [26] = { ["object"] = "prop_mil_crate_02", ["price"] = 100, ["name"] = "Caixa Militar" },
    [27] = { ["object"] = "prop_ld_int_safe_01", ["price"] = 1100, ["name"] = "Cofre" },
  },

  ["Eletrónica"] = {
    [1] = { ["object"] = "prop_trailr_fridge", ["price"] = 50, ["name"] = "Frigorifico" },
    [2] = { ["object"] = "v_res_fh_speaker", ["price"] = 50, ["name"] = "Colunas" },
    [3] = { ["object"] = "v_res_fh_speakerdock", ["price"] = 50, ["name"] = "Mini Coluna" },
    [4] = { ["object"] = "v_res_fh_bedsideclock", ["price"] = 50, ["name"] = "Relogio De Cama" },
    [5] = { ["object"] = "v_res_fa_phone", ["price"] = 50, ["name"] = "Telemovel" },
    [6] = { ["object"] = "v_res_fh_towerfan", ["price"] = 50, ["name"] = "Ventoinha" },
    [7] = { ["object"] = "v_res_fa_fan", ["price"] = 50, ["name"] = "Ventoinha" },
    [8] = { ["object"] = "v_res_lest_bigscreen", ["price"] = 50, ["name"] = "Tela" },
    [9] = { ["object"] = "v_res_lest_monitor", ["price"] = 50, ["name"] = "Monitor" },
    [10] = { ["object"] = "v_res_tre_mixer", ["price"] = 50, ["name"] = "Mixer" },
    [11] = { ["object"] = "prop_cs_cctv", ["price"] = 100, ["name"] = "CCTV" },
    [12] = { ["object"] = "prop_ld_lap_top", ["price"] = 100, ["name"] = "Portátil" },
    [13] = { ["object"] = "prop_ld_monitor_01", ["price"] = 100, ["name"] = "Monitor" },
    [14] = { ["object"] = "xm_prop_x17_tv_flat_02", ["price"] = 500, ["name"] = "TV" },
    [15] = { ["object"] = "apa_mp_h_str_avunitm_03", ["price"] = 1000, ["name"] = "TV set 1" },
    [16] = { ["object"] = "apa_mp_h_str_avunits_01", ["price"] = 1000, ["name"] = "TV set 2" },
    [17] = { ["object"] = "apa_mp_h_str_avunits_04", ["price"] = 1000, ["name"] = "TV set 3" },
    [18] = { ["object"] = "bkr_prop_clubhouse_jukebox_02a", ["price"] = 1000, ["name"] = "Jukebox" },
    [19] = { ["object"] = "bkr_prop_weed_fan_floor_01a", ["price"] = 50, ["name"] = "Ventoinha" },
    [20] = { ["object"] = "prop_cs_keyboard_01", ["price"] = 50, ["name"] = "Teclado" },
    [21] = { ["object"] = "ex_mp_h_acc_coffeemachine_01", ["price"] = 500, ["name"] = "Máquina de Café" },
  },

  ["Luz"] = {
    [1] = { ["object"] = "v_corp_cd_desklamp", ["price"] = 100, ["name"] = "Candeeiro Escritório 1" },
    [2] = { ["object"] = "v_res_desklamp", ["price"] = 100, ["name"] = "Candeeiro Escritório 1" },
    [3] = { ["object"] = "v_res_d_lampa", ["price"] = 100, ["name"] = "Candeeiro AA" },
    [4] = { ["object"] = "v_res_fa_lamp1on", ["price"] = 100, ["name"] = "Candeeiro 1" },
    [5] = { ["object"] = "v_res_fh_floorlamp", ["price"] = 100, ["name"] = "Candeeiro Chão" },
    [6] = { ["object"] = "v_res_fh_lampa_on", ["price"] = 100, ["name"] = "Candeeiro 2" },
    [7] = { ["object"] = "v_res_j_tablelamp1", ["price"] = 100, ["name"] = "Candeeiro Mesa 1" },
    [8] = { ["object"] = "v_res_j_tablelamp2", ["price"] = 100, ["name"] = "Candeeiro Mesa 1" },
    [9] = { ["object"] = "v_res_mdbedlamp", ["price"] = 100, ["name"] = "Candeeiro Cama" },
    [10] = { ["object"] = "v_res_mplanttongue", ["price"] = 100, ["name"] = "Candeeiro Planta" },
    [11] = { ["object"] = "v_res_mtblelampmod", ["price"] = 100, ["name"] = "Candeeiro Mesa 3" },
    [12] = { ["object"] = "v_res_m_lampstand", ["price"] = 100, ["name"] = "Suporte Candeeiro 1" },
    [13] = { ["object"] = "v_res_m_lampstand2", ["price"] = 100, ["name"] = "Suporte Candeeiro 2" },
    [14] = { ["object"] = "v_res_m_lamptbl", ["price"] = 100, ["name"] = "Candeeiro Mesa 4" },
    [15] = { ["object"] = "v_res_tre_lightfan", ["price"] = 100, ["name"] = "Luz Ventoinha" },
    [16] = { ["object"] = "v_res_tre_talllamp", ["price"] = 100, ["name"] = "Candeeiro Alto" },
    [17] = { ["object"] = "v_ret_fh_walllighton", ["price"] = 100, ["name"] = "Luz Parede" },
    [18] = { ["object"] = "v_ret_gc_lamp", ["price"] = 100, ["name"] = "Candeeiro GC" },
    [19] = { ["object"] = "prop_dummy_light", ["price"] = 100, ["name"] = "Luz Piscar" },
    [20] = { ["object"] = "prop_ld_cont_light_01", ["price"] = 100, ["name"] = "Candeeiro Lateral Parede" },
    [21] = { ["object"] = "V_44_D_emis", ["price"] = 100, ["name"] = "Luz Teste" },
  },


  ["Mesas"] = {
    [1] = { ["object"] = "v_res_d_coffeetable", ["price"] = 30, ["name"] = "Mesa Café 1" },
    [2] = { ["object"] = "v_res_d_roundtable", ["price"] = 30, ["name"] = "Mesa Redonda" },
    [3] = { ["object"] = "v_res_d_smallsidetable", ["price"] = 30, ["name"] = "Mesa De Cabeceira Pequena" },
    [4] = { ["object"] = "v_res_fh_coftablea", ["price"] = 30, ["name"] = "Mesa A" },
    [5] = { ["object"] = "v_res_fh_coftableb", ["price"] = 30, ["name"] = "Mesa B" },
    [6] = { ["object"] = "v_res_fh_coftbldisp", ["price"] = 30, ["name"] = "Mesa C" },
    [7] = { ["object"] = "v_res_fh_diningtable", ["price"] = 30, ["name"] = "Mesa Jantar" },
    [8] = { ["object"] = "v_res_j_coffeetable", ["price"] = 30, ["name"] = "Mesa Café 2" },
    [9] = { ["object"] = "v_res_j_lowtable", ["price"] = 30, ["name"] = "Mesa Baixa" },
    [10] = { ["object"] = "v_res_mdbedtable", ["price"] = 30, ["name"] = "Mesa Cabeceira 1" },
    [11] = { ["object"] = "v_res_mddesk", ["price"] = 30, ["name"] = "Secretária" },
    [12] = { ["object"] = "v_res_msidetblemod", ["price"] = 30, ["name"] = "Mesa Cabeceira 1" },
    [13] = { ["object"] = "v_res_m_console", ["price"] = 30, ["name"] = "Mesa Para Consola" },
    [14] = { ["object"] = "v_res_m_dinetble_replace", ["price"] = 30, ["name"] = "Mesa Jantar 2" },
    [15] = { ["object"] = "v_res_m_h_console", ["price"] = 30, ["name"] = "Mesa Para Consola 2" },
    [16] = { ["object"] = "v_res_m_stool", ["price"] = 30, ["name"] = "Banco" },
    [17] = { ["object"] = "v_res_tre_sideboard", ["price"] = 30, ["name"] = "Mesa Com Arrumação" },
    [18] = { ["object"] = "v_res_tre_table2", ["price"] = 30, ["name"] = "Mesa 2" },
    [19] = { ["object"] = "v_res_tre_tvstand", ["price"] = 30, ["name"] = "Mesa TV" },
    [20] = { ["object"] = "v_res_tre_tvstand_tall", ["price"] = 30, ["name"] = "Mesa TV Alta" },
    [21] = { ["object"] = "v_med_p_coffeetable", ["price"] = 30, ["name"] = "Mesa Café 3" },
    [22] = { ["object"] = "v_med_p_desk", ["price"] = 30, ["name"] = "Secretária 2" },
    [23] = { ["object"] = "prop_yacht_table_01", ["price"] = 100, ["name"] = "Mesa Iate 1" },
    [24] = { ["object"] = "prop_yacht_table_02", ["price"] = 100, ["name"] = "Mesa Iate 2" },
    [25] = { ["object"] = "prop_yacht_table_03", ["price"] = 100, ["name"] = "Mesa Iate 3" },
    [26] = { ["object"] = "v_ret_csr_table", ["price"] = 100, ["name"] = "Mesa CSR" },
    [27] = { ["object"] = "hei_heist_din_table_06", ["price"] = 100, ["name"] = "Mesa Jantar Com Cadeiras" },
  },

  ["Plantas"] = {
    [1] = { ["object"] = "prop_fib_plant_01", ["price"] = 60, ["name"] = "Planta 2" },
    [2] = { ["object"] = "v_corp_bombplant", ["price"] = 170, ["name"] = "Planta Bomba" },    
    [3] = { ["object"] = "v_res_mflowers", ["price"] = 170, ["name"] = "Planta Flores" }, 
    [4] = { ["object"] = "v_res_mvasechinese", ["price"] = 170, ["name"] = "Planta Chinesa" }, 
    [5] = { ["object"] = "v_res_m_bananaplant", ["price"] = 170, ["name"] = "Planta Banana" }, 
    [6] = { ["object"] = "v_res_m_palmplant1", ["price"] = 170, ["name"] = "Planta Palma" },  
    [7] = { ["object"] = "v_res_m_palmstairs", ["price"] = 170, ["name"] = "Planta Palma 2" },  
    [8] = { ["object"] = "v_res_m_urn", ["price"] = 170, ["name"] = "Planta 2" },  
    [9] = { ["object"] = "v_res_rubberplant", ["price"] = 170, ["name"] = "Planta Borracha" }, 
    [10] = { ["object"] = "v_res_tre_plant", ["price"] = 170, ["name"] = "Planta" }, 
    [11] = { ["object"] = "v_res_tre_tree", ["price"] = 170, ["name"] = "Planta Árvore" }, 
    [12] = { ["object"] = "v_med_p_planter", ["price"] = 170, ["name"] = "Planta 3" }, 
    [13] = { ["object"] = "v_ret_flowers", ["price"] = 100, ["name"] = "Flores" },
    [14] = { ["object"] = "v_ret_j_flowerdisp", ["price"] = 100, ["name"] = "Flores 1" },
    [15] = { ["object"] = "v_ret_j_flowerdisp_white", ["price"] = 100, ["name"] = "Flores 2" },
    [16] = { ["object"] = "apa_mp_h_acc_vase_flowers_01", ["price"] = 100, ["name"] = "Flores 3" },
    [17] = { ["object"] = "apa_mp_h_acc_vase_flowers_02", ["price"] = 100, ["name"] = "Flores 4" },
    [18] = { ["object"] = "xm_prop_x17_xmas_tree_int", ["price"] = 30, ["name"] = "Árvore De Natal" },
  },

  ["Cozinha"] = {
    [1] = { ["object"] = "prop_washer_01", ["price"] = 60, ["name"] = "Máquina Lavar 1" },
    [2] = { ["object"] = "prop_washer_02", ["price"] = 60, ["name"] = "Máquina Lavar 2" },
    [3] = { ["object"] = "prop_washer_03", ["price"] = 60, ["name"] = "Máquina Lavar 3" },
    [4] = { ["object"] = "prop_washing_basket_01", ["price"] = 60, ["name"] = "Cesto Roupa Suja" },
    [5] = { ["object"] = "v_res_fridgemoda", ["price"] = 60, ["name"] = "Frigorífico 1" },
    [6] = { ["object"] = "v_res_fridgemodsml", ["price"] = 60, ["name"] = "Frigorífico 2" },
    [7] = { ["object"] = "prop_fridge_01", ["price"] = 60, ["name"] = "Frigorífico 3" },
    [8] = { ["object"] = "prop_fridge_03", ["price"] = 60, ["name"] = "Frigorífico 4" },
    [9] = { ["object"] = "prop_cooker_03", ["price"] = 60, ["name"] = "Fogão" },
    [10] = { ["object"] = "prop_micro_01", ["price"] = 60, ["name"] = "Microondas 1" },
    [11] = { ["object"] = "prop_micro_02", ["price"] = 60, ["name"] = "Microondas 2" },
    [12] = { ["object"] = "prop_wok", ["price"] = 60, ["name"] = "Wok" },
    [13] = { ["object"] = "v_res_cakedome", ["price"] = 60, ["name"] = "Prato Bolos" },
    [14] = { ["object"] = "v_res_fa_chopbrd", ["price"] = 60, ["name"] = "Tábua Cortar" },
    [15] = { ["object"] = "v_res_mutensils", ["price"] = 60, ["name"] = "Utensílios" },
    [16] = { ["object"] = "v_res_pestle", ["price"] = 60, ["name"] = "Pilão" },
    [17] = { ["object"] = "v_ret_ta_paproll", ["price"] = 60, ["name"] = "Papel Cozinha 1" },
    [18] = { ["object"] = "v_ret_ta_paproll2", ["price"] = 60, ["name"] = "Papel Cozinha 2" },
    [19] = { ["object"] = "v_ret_fh_pot01", ["price"] = 60, ["name"] = "Tacho 1" },
    [20] = { ["object"] = "v_ret_fh_pot02", ["price"] = 60, ["name"] = "Tacho 2" },
    [21] = { ["object"] = "v_ret_fh_pot05", ["price"] = 60, ["name"] = "Tacho 3" },
    [22] = { ["object"] = "prop_pot_03", ["price"] = 60, ["name"] = "Tacho 4" },
    [23] = { ["object"] = "prop_pot_04", ["price"] = 60, ["name"] = "Tacho 5" },
    [24] = { ["object"] = "prop_pot_05", ["price"] = 60, ["name"] = "Tacho 6" },
    [25] = { ["object"] = "prop_pot_06", ["price"] = 60, ["name"] = "Tacho 7" },
    [26] = { ["object"] = "prop_pot_rack", ["price"] = 60, ["name"] = "Boca Tacho" },
    [27] = { ["object"] = "prop_kitch_juicer", ["price"] = 60, ["name"] = "Liquidificadora" },
  },


  ["Casa de Banho"] = {
    [1] = { ["object"] = "prop_ld_toilet_01", ["price"] = 100, ["name"] = "Sanita 1" },
    [2] = { ["object"] = "prop_toilet_01", ["price"] = 100, ["name"] = "Sanita 2" },
    [3] = { ["object"] = "prop_toilet_02", ["price"] = 100, ["name"] = "Sanita 3" },
    [4] = { ["object"] = "prop_sink_02", ["price"] = 100, ["name"] = "Lavatório 1" },
    [5] = { ["object"] = "prop_sink_04", ["price"] = 100, ["name"] = "Lavatório 2" },
    [6] = { ["object"] = "prop_sink_05", ["price"] = 100, ["name"] = "Lavatório 3" },
    [7] = { ["object"] = "prop_sink_06", ["price"] = 100, ["name"] = "Lavatório 4" },
    [8] = { ["object"] = "prop_soap_disp_01", ["price"] = 100, ["name"] = "Dispensador De Sabão" },
    [9] = { ["object"] = "prop_shower_rack_01", ["price"] = 100, ["name"] = "Suporte Banho" },
    [10] = { ["object"] = "prop_handdry_01", ["price"] = 100, ["name"] = "Secador Mãos 1" },
    [11] = { ["object"] = "prop_handdry_02", ["price"] = 100, ["name"] = "Secador Mãos 2" },
    [12] = { ["object"] = "prop_towel_rail_01", ["price"] = 100, ["name"] = "Suporte Toalha 1" },
    [13] = { ["object"] = "prop_towel_rail_02", ["price"] = 100, ["name"] = "Suporte Toalha 2" },
    [14] = { ["object"] = "prop_towel_01", ["price"] = 100, ["name"] = "Toalha 1" },
    [15] = { ["object"] = "v_res_mbtowel", ["price"] = 100, ["name"] = "Toalha 2" },
    [16] = { ["object"] = "v_res_mbtowelfld", ["price"] = 100, ["name"] = "Toalha 3" },
    [17] = { ["object"] = "v_res_mbath", ["price"] = 100, ["name"] = "Banheira" },
    [18] = { ["object"] = "v_res_mbsink", ["price"] = 100, ["name"] = "Lavatório" },
  },

  ["Items Médicos"] = {
    [1] = { ["object"] = "v_med_barrel", ["price"] = 750, ["name"] = "Barril Quimico" },
    [2] = { ["object"] = "v_med_apecrate", ["price"] = 750, ["name"] = "Caixa de Animais" },
    [3] = { ["object"] = "v_med_apecratelrg", ["price"] = 750, ["name"] = "Caixa Grande De Animais" },
    [4] = { ["object"] = "v_med_bed1", ["price"] = 750, ["name"] = "Cama1" },
    [5] = { ["object"] = "v_med_bed2", ["price"] = 750, ["name"] = "Cama2" },
    [6] = { ["object"] = "v_med_bedtable", ["price"] = 750, ["name"] = "Mesa De Cama" },
    [7] = { ["object"] = "v_med_bench1", ["price"] = 750, ["name"] = "Bancada1" },
    [8] = { ["object"] = "v_med_bench2", ["price"] = 750, ["name"] = "Bancada2" },
    [9] = { ["object"] = "v_med_benchcentr", ["price"] = 750, ["name"] = "Conjunto De Secretária" },
    [10] = { ["object"] = "v_med_benchset1", ["price"] = 750, ["name"] = "Mesa Grande" },
    [11] = { ["object"] = "v_med_bigtable", ["price"] = 750, ["name"] = "Big Table" },
    [12] = { ["object"] = "v_med_bin", ["price"] = 150, ["name"] = "Lixo2" },
    [13] = { ["object"] = "v_med_centrifuge1", ["price"] = 750, ["name"] = "Centrífuga" },
    [14] = { ["object"] = "v_med_cooler", ["price"] = 750, ["name"] = "Refrigerador" },
    [15] = { ["object"] = "v_med_cor_ceilingmonitor", ["price"] = 750, ["name"] = "Monitor" },
    [16] = { ["object"] = "v_med_cor_autopsytbl", ["price"] = 750, ["name"] = "Mesa De Autopsia" },
    [17] = { ["object"] = "v_med_cor_cembin", ["price"] = 750, ["name"] = "Lixo" },
    [18] = { ["object"] = "v_med_cor_cemtrolly2", ["price"] = 750, ["name"] = "Carrinho De Prateleiras" },
    [19] = { ["object"] = "v_med_cor_chemical", ["price"] = 750, ["name"] = "Garrafão de Quimicos" },
    [20] = { ["object"] = "v_med_cor_emblmtable", ["price"] = 750, ["name"] = "Mesa Médica" },
    [21] = { ["object"] = "v_med_cor_fileboxa", ["price"] = 750, ["name"] = "Caixa De Ficheiros" },
    [22] = { ["object"] = "v_med_cor_filingcab", ["price"] = 750, ["name"] = "Prateleira de Ficheiros" },
    [23] = { ["object"] = "v_med_cor_hose", ["price"] = 750, ["name"] = "Mangueira" },
    [24] = { ["object"] = "v_med_cor_largecupboard", ["price"] = 750, ["name"] = "Armário Grande" },
    [25] = { ["object"] = "v_med_cor_lightbox", ["price"] = 750, ["name"] = "Caixa De Luz" },
    [26] = { ["object"] = "v_med_cor_medstool", ["price"] = 750, ["name"] = "Banco De Médico" },
    [27] = { ["object"] = "v_med_cor_minifridge", ["price"] = 750, ["name"] = "Mini Frigorifico" },
    [28] = { ["object"] = "v_med_cor_papertowels", ["price"] = 750, ["name"] = "Toalhas De Papel" },
    [29] = { ["object"] = "v_med_cor_photocopy", ["price"] = 750, ["name"] = "Fotocopiadora" },
    [30] = { ["object"] = "v_med_cor_tvstand", ["price"] = 750, ["name"] = "Suporte de TV" },
    [31] = { ["object"] = "v_med_cor_wallunita", ["price"] = 750, ["name"] = "Armários Médicos" },
    [32] = { ["object"] = "v_med_examlight", ["price"] = 750, ["name"] = "Luz De Exame" },
    [33] = { ["object"] = "v_med_gastank", ["price"] = 750, ["name"] = "Tanque de Gás" },
    [34] = { ["object"] = "v_med_hazmatscan", ["price"] = 750, ["name"] = "Hazmat Scan" },
    [35] = { ["object"] = "v_med_hospheadwall1", ["price"] = 750, ["name"] = "Cabeceira Hospitalar" },
    [36] = { ["object"] = "v_med_hospseating1", ["price"] = 750, ["name"] = "Assento" },
    [37] = { ["object"] = "v_med_hosptable", ["price"] = 750, ["name"] = "Mesa De Hospital" },
    [38] = { ["object"] = "v_med_latexgloveboxblue", ["price"] = 50, ["name"] = "Caixa De Luvas" },
    [39] = { ["object"] = "v_med_medwastebin", ["price"] = 750, ["name"] = "Balde De Lixo" },
    [40] = { ["object"] = "v_med_oscillator3", ["price"] = 750, ["name"] = "Osciloscópio" },
    [41] = { ["object"] = "prop_ld_health_pack", ["price"] = 100, ["name"] = "Kit Médico" },
  }
}


lookuptable = {}
dropdowntable = {}
hashtable = {}

for category,v in pairs(furni.objects) do 
  dropdowntable[category] = {}

  for o,k in pairs(v) do

    local hash = GetHashKey(k.object)
    hashtable[hash] = k
  
    local id = k.object or "none"
    local name = k.name or "none"
    local price = k.price or 9999

    lookuptable[id] = k

    table.insert(dropdowntable[category],{id = id,name = name,price = price})
  end 
end 

for k,v in pairs(furni.objects) do
  for k,v in pairs(v) do
    v.id = v.object
  end
end

if not Config.UsingNativeHousing then
  TriggerEvent('esx:getSharedObject', function(obj) ESX = obj; end)
  Citizen.CreateThread(function(...) while not ESX do TriggerEvent('esx:getSharedObject',function(obj) ESX = obj; end); Citizen.Wait(0); end; end)
end

mLibs = exports["meta_libs"]